name: teego
description: Live Streaming app

publish_to: 'none'

version: 9.0.0+9
environment:
  sdk: ">=2.13.0 <3.0.3"

dependencies:

  flutter:
    sdk: flutter

  #Default
#  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
#  window_manager:


  #Images
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  image_cropper: ^3.0.1
  blur: ^3.1.0
  video_editor: ^2.4.0
  wechat_assets_picker: ^8.4.0
  wechat_camera_picker: ^3.7.0
  flutter_image_compress: ^1.1.3
  cached_video_player: ^2.0.2
#  cached_video_player: ^2.0.4
  mime: ^1.0.4
  preload_page_view: ^0.1.6
  like_button: ^2.0.5
  loading_animation_widget: ^1.2.0+4
#  sliding_clipped_nav_bar: ^3.1.0+4
  path_provider: ^2.0.13
  responsive_sizer:
  firebase_storage:
  image_picker:
  story_view:
#  timer_builder:
  text_editor:
  #Backend
  parse_server_sdk_flutter: ^3.1.3
  persistent_bottom_nav_bar: ^4.0.2
  #State management
  provider: ^6.0.5

  #Utilities
  easy_localization: ^3.0.1
  flutter_native_splash: ^2.2.19
  webview_flutter: ^4.0.6
  url_launcher: ^6.1.10
  universal_platform: ^1.0.0+1
  devicelocale: ^0.6.0
  shared_preferences: ^2.0.18
  url_strategy: ^0.2.0
  permission_handler: ^10.2.0
  #  share_plus: ^6.3.1
#  stop_watch_timer: ^2.0.0
#  flutter_windowmanager: ^0.2.0
  fade_shimmer: ^2.2.0

#  sticky_grouped_list: ^3.1.0
#
#  iban: ^1.0.1
  flutter_svg_provider:

  whatsapp_unilink: ^2.1.0
  keyboard_attachable: ^2.1.0
#  just_audio: ^0.9.31
  helpers: ^1.2.0
  upgrader: ^6.0.1 #Dont upgrade it for Parse Server package
#  flutter_staggered_grid_view: ^0.6.2

  #Calls and live streaming
  #agora_rtc_engine: ^6.0.0
#  agora_rtc_engine: ^5.3.0 #Dont upgrade it
#  agora_rtm: ^1.5.0
#  flutter_ringtone_player: ^3.2.0
  #flutter_webrtc: ^0.9.21
  #callkeep: ^0.3.3
#  flutter_callkit_incoming: ^1.0.3+3

  #Geo data and phone helper
  country_provider: ^1.0.2
#  intl_phone_number_input: ^0.7.2
#  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  location: ^4.4.0

  #Animations and icons
  #  flutter_icons: 1.1.0
  lottie: ^2.3.0

  #Firebase
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  firebase_analytics: ^10.1.5
  firebase_performance: ^0.9.0+15
  firebase_crashlytics: ^3.0.16
  firebase_dynamic_links: ^5.0.16

  #push notifications
  another_flushbar: ^1.12.29

  #Social login
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^5.0.8

  #payments:
#  purchases_flutter: ^4.10.4
  purchases_flutter: ^6.29.4

  # fake name
#  faker: ^2.1.0

  #Ads
  google_mobile_ads: ^2.3.0
  app_tracking_transparency: ^2.0.3

  #Libraries
  xml: ^6.2.2
  flutter_linkify: ^5.0.2
#  marquee: ^2.2.3
#  hashtagable: ^2.1.0
  flutter_stripe:
  cloud_firestore: ^4.8.1
  flutter_dotenv: ^5.1.0
#  change_app_package_name: ^1.1.0
  stripe_ios: ^9.2.1
  flutter_screenutil: ^5.7.0
#  advstory: ^0.2.1
#  flutter_instagram_stories: ^1.0.2
  get: ^4.6.5
#  convex_bottom_bar: ^3.2.0
#  circle_nav_bar: ^2.0.1+1
#  molten_navigationbar_flutter: ^1.0.1
#  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  audioplayers: ^4.1.0

  share_plus:

  wakelock: ^0.6.2
  fluttertoast:


  zego_express_engine: ^3.6.1
  zego_zim: ^2.9.0
  encrypt: ^5.0.1
#  zego_zim: ^2.12.0
#  zego_express_engine: ^3.9.0
#  flutter_layout_grid: ^2.0.5
  flutter_staggered_grid_view: ^0.4.0
#  video_player: ^2.7.2


  svgaplayer_flutter: ^2.2.0
  dio:
  camera: ^0.10.5+5
  flutter_cache_manager: ^3.3.1
  flutter_animation_progress_bar:
  youtube_player_flutter:

  sticky_grouped_list: ^3.1.0
  device_info_plus:
  english_words:
  syncfusion_flutter_sliders:

  just_audio: ^0.9.31

  flutter_keyboard_visibility:
#  ed_screen_recorder:
  screenshot: ^1.1.0
  carousel_slider: ^4.2.1







  confetti:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/reels/
    - assets/png/
    - assets/translations/
    - assets/flags/
#    - assets/livestreaming/
#    - assets/userview/
#    - assets/pk_battle/
#    - assets/gifts/
#    - assets/explore/
#    - assets/dino/
#    - assets/avatar/
#    - assets/chat/
    - assets/png/Chat/
    - assets/png/dashboard/
    - assets/png/userProfile/
    - assets/png/streamerProfile/
    - assets/png/streamer/
    - assets/png/streamer/battle/
    - assets/svga/
    - assets/audios/
    - assets/png/audience/
    - assets/png/audience/gifts/
    - assets/png/game/
    - assets/animations/
    - assets/animations/battle/
    - assets/svg/America_Region_Flags/
    - assets/svg/Asia_Region_Flags/
    - assets/svg/Europe_Region_Flags/
    - assets/svg/Middle_East_Region_Flags/
    - assets/png/streamer/liveCreate/
    - assets/png/streamer/multiGuestStreamer/
    - assets/png/streamer/liveStreamer/
    - assets/png/top_streams/
    - assets/png/trending/
    - assets/png/home/
    - assets/png/setting/
    - assets/svg/avatar_frame/
    - assets/png/background/
    - assets/png/room_decor/



  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
          weight: 300

    - family: Quinlliyk
      fonts:
        - asset: assets/fonts/Quinlliyk-Regular.ttf
          weight: 400

dependency_overrides:
  parse_server_sdk: ^3.1.3
  package_info_plus: ^3.0.3
  #  camera_android: ^0.10.4+3
  #dio: ^5.0.2

flutter_native_splash:
  color: "#0071e5"
  image: assets/page-1/images/LOGO.png
  #branding: assets/branding-production.png
  color_dark: "#000000"
  image_dark: assets/page-1/images/LOGO.png
  #branding_dark: assets/branding-production.png

  android_12:
    image: assets/page-1/images/LOGO.png
    icon_background_color: "#0071e5"
    image_dark: assets/page-1/images/LOGO.png
    icon_background_color_dark: "#000000"

  web: false